# Name of workflow
name: My Test workflow

# Define the trigger events
on: [push]

# Jobs run in parallel by default, each runs steps in sequence
jobs:
  #Job to print something out
  say-hello:
    # The type of machine to run the job on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks to be executed
    steps:
      - run: echo "Hello, Github Actions!"