# Name of workflow
name: My Test workflow

# Define the trigger events
on: [push]

# Jobs run in parallel by default, each runs steps in sequence
jobs:
  #Job to print something out
  say-hello:
    # The type of machine to run the job on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks to be executed
    steps:
      - name: Say Hello
        # Run a single command using the runners shell
        run: echo "Hello, Github Actions!"

  # Job to build and test our C code
  needs: [say-hello]
  runs-on: ubuntu-latest
  steps:
    # User github.com/actions/checkout to chec out this repo
    - name: Check out this repo
      uses: actions/checkout@v3
    
    # Install necessary packages
    - name: Install dependencies
      run: sudo apt install -y build-essential python3

    # See where we are in the VM
    - run: pwd

    # Run our test
    - name: Run test
      run: python3 test.py

    